####################################
# APPLICATION
####################################
server.port=8080

####################################
# DATABASE (PostgreSQL)
####################################
spring.datasource.url=jdbc:postgresql://localhost:5432/educhain_db
spring.datasource.username=postgres
spring.datasource.password=714522
spring.datasource.driver-class-name=org.postgresql.Driver

####################################
# JPA / HIBERNATE
####################################
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

####################################
# MULTIPART (PDF upload)
####################################
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

####################################
# HASH
####################################
educhain.hash-algorithm=SHA-256

####################################
# BLOCKCHAIN (SEPOLIA)
####################################
educhain.web3.rpc=https://sepolia.infura.io/v3/9c3cc6097ce842baac531f8133648a29

# Senin deploy etti?in contract
educhain.contract.address=0x217bDCC727266C60E08c5a5e05CdbF4651Cc3A58

# ??lemleri gönderecek cüzdan?n private key'i
educhain.issuer.private-key=1d892b170bd5866546b49486ae5998f49101509fa101a2d15b05c5563152f870

####################################
# JWT
####################################
jwt.secret=EduChainSuperSecretKeyForJwtToken1234567890
jwt.expiration=86400000